[terminal]
[terminal.shell]
program = "/usr/bin/tmux"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

[scrolling]
history = 100000

[general]
import = ["~/.config/alacritty/current-theme.toml"]
